In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv')

In [4]:
df.head(10)

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...
5,BI,can you help me cancel order {{Order Number}}?,ORDER,cancel_order,"Of course, I'm here to assist you in canceling..."
6,BCLN,"I can no longer afford order {{Order Number}},...",ORDER,cancel_order,I pick up what you're putting down that you're...
7,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I've understood that you're seeking assistance...
8,BL,I have got to cancel purchase {{Order Number}},ORDER,cancel_order,I'm sensitive to the fact that you're seeking ...
9,BLQ,i need help canceling purchase {{Order Number}},ORDER,cancel_order,I perceive that you're seeking assistance with...

In [5]:
print(df.shape)
df.describe()

(26872, 5)

,flags,instruction,category,intent,response
count,26872,26872,26872,26872,26872
unique,394,24635,11,27,26870
top,BL,do you ship to {{Delivery City}}?,ACCOUNT,check_invoice,"Firstly, I truly understand how pivotal the {{..."
freq,5212,8,5986,1000,2

In [6]:
print(f"Category Unique Values: \n{df['category'].unique()}")
print(f"\n Intent Unique Values:\n{df['intent'].unique()}")

Category Unique Values:
<StringArray>
[       'ORDER',     'SHIPPING',       'CANCEL',      'INVOICE',
      'PAYMENT',       'REFUND',     'FEEDBACK',      'CONTACT',
      'ACCOUNT',     'DELIVERY', 'SUBSCRIPTION']
Length: 11, dtype: str

 Intent Unique Values:
<StringArray>
[            'cancel_order',             'change_order',
  'change_shipping_address',   'check_cancellation_fee',
            'check_invoice',    'check_payment_methods',
      'check_refund_policy',                'complaint',
 'contact_customer_service',      'contact_human_agent',
           'create_account',           'delete_account',
         'delivery_options',          'delivery_period',
             'edit_account',              'get_invoice',
               'get_refund',  'newsletter_subscription',
            'payment_issue',              'place_order',
         'recover_password',    'registration_problems',
                   'review',  'set_up_shipping_address',
           'switch_account',              'track_order',
             'track_refund']
Length: 27, dtype: str

In [7]:
df.loc[df['category'] == "CANCEL"]

,flags,instruction,category,intent,response
2968,BCLWZ,"I can't ifnd the bloody termination charge, I ...",CANCEL,check_cancellation_fee,No worries! I'll assist you in finding the ter...
2969,BIL,what is the fee for canceling the contract?,CANCEL,check_cancellation_fee,To inquire about the cancellation fee for your...
2970,BILP,could I check the withdrawal charge?,CANCEL,check_cancellation_fee,Positively! I can help you with the informatio...
2971,BLQ,i need help to see the early termination penalty,CANCEL,check_cancellation_fee,Absolutely! To view the early termination pena...
2972,BLQ,need assistance to see the withdrawal fee,CANCEL,check_cancellation_fee,Indeed! I'm here to help you with checking the...
...,...,...,...,...,...
3913,BCLM,"I have to see the early termination fees, help me",CANCEL,check_cancellation_fee,"Sure, I can assist you with checking the early..."
3914,BCLZ,"I want to check the termination fee , help me",CANCEL,check_cancellation_fee,Unquestionably! To check the termination fee f...
3915,BIL,can you help me to see the withdrawal charge?,CANCEL,check_cancellation_fee,"For sure! To view the withdrawal charge, you c..."
3916,BLQZ,i have got to check the early exit pnalty,CANCEL,check_cancellation_fee,I'll make it happen! I can assist you with ver...
3917,BILM,can you help me see the cancellation charges?,CANCEL,check_cancellation_fee,Absolutely! I'd be happy to assist you in veri...

*****USE instruction and category to predict intent*****

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
features = ['instruction', 'category']
X = df[features]
y = df['intent']

In [10]:
X.isna().value_counts()
df[features].isna().value_counts()
df['intent'].unique()

<StringArray>
[            'cancel_order',             'change_order',
  'change_shipping_address',   'check_cancellation_fee',
            'check_invoice',    'check_payment_methods',
      'check_refund_policy',                'complaint',
 'contact_customer_service',      'contact_human_agent',
           'create_account',           'delete_account',
         'delivery_options',          'delivery_period',
             'edit_account',              'get_invoice',
               'get_refund',  'newsletter_subscription',
            'payment_issue',              'place_order',
         'recover_password',    'registration_problems',
                   'review',  'set_up_shipping_address',
           'switch_account',              'track_order',
             'track_refund']
Length: 27, dtype: str

In [11]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y,
                                                      train_size=0.8,
                                                      random_state=0)

In [12]:
X_train.head()

                                             instruction  category
10657  i want help to open a {{Account Category}} acc...   ACCOUNT
22965  there is a trouble submitting a secondary ship...  SHIPPING
23595                 I cannot set a shipping address up  SHIPPING
369              I do not want purchase {{Order Number}}     ORDER
16863  i have paid {{Currency Symbol}}{{Refund Amount...    REFUND

Model built using a RandomForestClassifier

In [13]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), features)],
    remainder='passthrough'
)

pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(n_estimators=100, oob_score=True, random_state=0))
])
pipe.fit(X_train, y_train)
print("OOB Score: " + str(pipe.named_steps['model'].oob_score_))

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import classification_report, accuracy_score
preds = pipe.predict(X_valid)
print(f"Accuracy Score: {accuracy_score(y_valid, preds)}")
print(classification_report(y_valid, preds))

***Use tfidfvectorizer***

***OneHotEncoding Categorical Columns and Training with a RandomForestClassifier has 50% accuracy model***

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_preprocessor = ColumnTransformer(
    transformers=[
        ('subject_tfidf', TfidfVectorizer(stop_words='english', max_features=500), 'category'),
        ('desc_tfidf', TfidfVectorizer(stop_words='english', max_features=1000), 'instruction')
    ],
    remainder='passthrough'
)

In [ ]:
pipe_2 = Pipeline(steps=[
    ('preprocessor', tfidf_preprocessor),
    ('model', RandomForestClassifier(n_estimators=500, oob_score=True, random_state=0))
])

pipe_2.fit(X_train, y_train)

preds_2 = pipe_2.predict(X_valid)
print("OOB Score with TfidfVectorizer: " + str(pipe_2.named_steps['model'].oob_score_))

In [ ]:
print(f"Accuracy Score: {accuracy_score(y_valid, preds_2)}")
print(classification_report(y_valid, preds_2))

***Vectorizing Columns with TfidfVectorizer makes the model have 98% accuracy on training and validation sets!***

Try Running a Gridsearchcv to find the best parameter combinations and see if the model can be more accurate

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__n_estimators': [200, 500],
    'model__max_depth': [20, 50, None],
    'model__min_samples_split': [2, 5, 10],
    'model__max_features': ['sqrt', 'log2']
}
grid_search = GridSearchCV(pipe_2, param_grid, cv=3, scoring='accuracy', verbose=1)
grid_search.fit(X_train, y_train)

print(f"Best Score: {grid_search.best_score_}")
print(f"Best Params: {grid_search.best_params_}")

In [ ]:
grid_preds = grid_search.predict(X_valid)
print(f"Accuracy Score: {accuracy_score(y_valid, grid_preds)}")
print(classification_report(y_valid, grid_preds))

***The model is 98% accurate after finding the best parameters with a GridSearch

In [16]:
df['category'].unique()

<StringArray>
[       'ORDER',     'SHIPPING',       'CANCEL',      'INVOICE',
      'PAYMENT',       'REFUND',     'FEEDBACK',      'CONTACT',
      'ACCOUNT',     'DELIVERY', 'SUBSCRIPTION']
Length: 11, dtype: str